const codeTypes = {
  text: 'Text',
  asp: 'ASP',
  c: 'C',
  coffeescript: 'CoffeeScript',
  clojure: 'Clojure',
  cplusplus: 'C++',
  csharp: 'C#',
  css: 'CSS',
  curl: 'cURL',
  cypher: 'Cypher',
  d: 'D',
  erlang: 'Erlang',
  go: 'Go',
  groovy: 'Groovy',
  handlebars: 'Handlebars',
  haml: 'HAML',
  haxe: 'Haxe',
  html: 'HTML',
  http: 'HTTP',
  java: 'Java',
  javascript: 'JavaScript',
  jinja2: 'Jinja2',
  json: 'JSON',
  julia: 'Julia',
  less: 'LESS',
  liquid: 'Liquid',
  lua: 'Lua',
  markdown: 'Markdown',
  mysql: 'MySQL',
  objectivec: 'Objective-C',
  perl: 'Perl',
  php: 'PHP',
  pgsql: 'Postgres',
  python: 'Python',
  r: 'R',
  ruby: 'Ruby',
  rust: 'Rust',
  sass: 'SASS',
  scala: 'Scala',
  scss: 'SCSS',
  shell: 'Shell',
  smarty: 'Smarty',
  sql: 'SQL',
  stylus: 'Stylus',
  swift: 'Swift',
  toml: 'TOML',
  twig: 'Twig',
  xml: 'XML',
  yaml: 'YAML',
};

module.exports = function uppercase(language) {
  if (codeTypes[language]) return codeTypes[language];
  return language;
};
