export default {
  post:{color: 'green', bg: '#f6ffed', border: '#52c41a'},
  get: {color: 'blue', bg: '#e6f7ff', border: '#1890ff'},
  put: {color: 'orange', bg: '#fff7e6', border: '#fa8c16'},
  delete: {color: 'volcano', bg: '#fff2e8', border: '#fa541c'},
  patch: {color: 'cyan', bg: '#e6fffb', border: '#13c2c2'},
  head: {color: 'purple', bg: '#f9f0ff', border: '#d3adf7'},
  options: {color: 'geekblue', bg: '#f0f5ff', border: '#adc6ff'},
  defaultTag: '#fff',
  defaultBackground: '#fff',
  defaultBorder: '#a8a7a7',
  bold: '#666666',
  pathUrl: '#a8a7a7',
  pathVariable: '#5a5a5a',
  pathUrlShadow: 'rgba(81,88,90,0.17)',
  pathUrlBackground: '#f0f2f4',
  pathVariableBorder: '#ccc',
  inputColor: '#666',
  inputBorder: '#ddd',
  authType: '#a8a7a7',
  success: 'green',
  error: 'red',
  resultsTab: '#fff',
  descriptionBackground: '#33373a',
  descriptionText: '#747c84',
  blockWithTabSelected: '#000',
  blockWithTabList: '#333840',
  blockWithTabLink: 'rgba(255,255,255,0.4)',
  metadataLabel: 'rgba(255,255,255,.4)',
  metadataContent: '#fff',
  suggestEdit: '#aaaaaa',
  snippet: '#fff',
  reactJson: '#000',
  codeAndResponseBackground: 'rgb(51, 55, 58)',
  codeAndResponseBorder: '#0f0f0f',
  notJson: '#fff',
  white: '#fff',
  jsonViewerBackground: '#ededed',
  schemaTabSelectedItem: '#aeaeae',
  schemaTabItemColor: '#c4c4c4',
  schemaTabItemBorder: 'rgba(255,255,255,0)',
  schemaTabListBorder: '#ddd',
  schemaTabMissingSchemaBackground: '#ededed'
}
